[package]
name = "composite_mqtt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mqtt-v5 = "0.1.1"
bytes = "0.5.4"
